# Generated by Django 4.0.4 on 2022-05-26 09:32

from django.db import migrations, models
import pacientes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('data_nas', models.DateTimeField(blank=True, null=True)),
                ('rg', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('num_endereco', models.IntegerField(blank=True, null=True)),
                ('bairro_endereco', models.CharField(blank=True, max_length=60, null=True)),
                ('cep', models.CharField(blank=True, max_length=100, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=pacientes.models.foto_paciente)),
            ],
            options={
                'db_table': 'pacientes',
                'managed': True,
            },
        ),
    ]
