# Generated by Django 4.0.4 on 2022-05-31 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='id_paciente',
            new_name='id',
        ),
    ]
