# Generated by Django 4.0.4 on 2022-05-31 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_rename_id_paciente_pacientes_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='id',
            new_name='id_pacientes',
        ),
    ]
