# Generated by Django 4.0.4 on 2022-05-31 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_rename_id_pacientes_id_pacientes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='id_pacientes',
            new_name='id_paciente',
        ),
    ]
