# Generated by Django 4.0.4 on 2022-05-31 12:45

from django.db import migrations, models
import django.db.models.deletion
import pacientes.models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('imagens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoPaciente',
            fields=[
                ('id_foto_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('foto_paciente', models.ImageField(blank=True, null=True, upload_to=pacientes.models.foto_paciente)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='pacientes.pacientes')),
            ],
        ),
    ]
